name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      # Steps for checking out the code, setting up Rust, and building for Linux...
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build for Linux
        run: |
          cargo build --release
          mv target/release/balamod target/release/balamod-${{ github.ref_name }}-linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: balamod-${{ github.ref_name }}-linux
          path: target/release/balamod-${{ github.ref_name }}-linux

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      # Steps for checking out the code, setting up Rust, and building for Windows...
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Build for Windows
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          mv target/x86_64-pc-windows-gnu/release/balamod.exe target/x86_64-pc-windows-gnu/release/balamod-${{ github.ref_name }}-windows.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: balamod-${{ github.ref_name }}-windows
          path: target/x86_64-pc-windows-gnu/release/balamod-${{ github.ref_name }}-windows.exe


  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path_to_your_linux_artifact
          asset_name: balamod-${{ github.ref_name }}-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path_to_your_windows_artifact
          asset_name: balamod-${{ github.ref_name }}-windows.exe
          asset_content_type: application/octet-stream
